In [5]:
import numpy as np

In [2]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
height

[1.73, 1.68, 1.71, 1.89, 1.79]

In [3]:
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight

[65.4, 59.2, 63.6, 88.4, 68.7]

In [4]:
weight/height ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [6]:
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [7]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [8]:
bmi = np_weight/np_height**2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [9]:
list1 = [2, True]
np_list1 = np.array(list1)
np_list1

array([2, 1])

In [11]:
list2 = [1,2,3]
numpy_array = np.array(list2)
list2

[1, 2, 3]

In [12]:
list2 + list2

[1, 2, 3, 1, 2, 3]

In [13]:
numpy_array + numpy_array

array([2, 4, 6])

In [14]:
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [15]:
bmi[1]

20.97505668934241

In [16]:
bmi > 23

array([False, False, False,  True, False])

In [17]:
bmi[bmi > 23]

array([24.7473475])

In [18]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [19]:
np_baseball = np.array(baseball)
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [20]:
type(np_baseball)

numpy.ndarray

In [21]:
np_height_m = 0.254 * np_height
np_height_m

array([0.43942, 0.42672, 0.43434, 0.48006, 0.45466])

In [22]:
np_weight_kg = 0.453592 * np_weight
np_weight_kg

array([29.6649168, 26.8526464, 28.8484512, 40.0975328, 31.1617704])

In [23]:
bmi2 = np_weight_kg/np_height_m ** 2
bmi2

array([153.63264059, 147.4691226 , 152.91949246, 173.9909301 ,
       150.74698268])

In [26]:
light = bmi2 < 150
light

array([False,  True, False, False, False])

In [27]:
bmi2[light]

array([147.4691226])

In [29]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [30]:
bmi2[:]

array([153.63264059, 147.4691226 , 152.91949246, 173.9909301 ,
       150.74698268])

In [31]:
 np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                   [65.4, 59.2, 63.6, 88.4, 68.7]]) 

In [32]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [33]:
np_2d.shape

(2, 5)

In [34]:
 np.array([[1.73, 1.68, 1.71, 1.89, 1.79], 
           [65.4, 59.2, 63.6, 88.4, "68.7"]]) 

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [35]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [36]:
np_2d[0][2]

1.71

In [37]:
np_2d[0, 2]

1.71

In [38]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [39]:
baseball2 = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [40]:
np_baseball2 = np.array(baseball2)
np_baseball2

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [41]:
type(np_baseball2)

numpy.ndarray

In [42]:
np_baseball2.shape

(4, 2)

In [43]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
arr1 = np.sqrt(arr)
arr1

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [45]:
np.square(arr)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196], dtype=int32)

In [46]:
np.exp(arr1)

array([ 1.        ,  2.71828183,  4.11325038,  5.65223367,  7.3890561 ,
        9.35646902, 11.58243519, 14.09403011, 16.91882868, 20.08553692,
       23.62434292, 27.56714845, 31.94774551, 36.80196629, 42.16782067])

In [47]:
np.log(arr1[:])

C:\intelpython3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.34657359, 0.54930614, 0.69314718,
       0.80471896, 0.89587973, 0.97295507, 1.03972077, 1.09861229,
       1.15129255, 1.19894764, 1.24245332, 1.28247468, 1.31952866])

In [48]:
a = [5, 4, 9]
b = [3, 6, 8]

In [49]:
np.add(a, b)

array([ 8, 10, 17])

In [50]:
np.subtract(a, b)

array([ 2, -2,  1])

In [51]:
np.multiply(a, b)

array([15, 24, 72])

In [52]:
np.divide(a, b)

array([1.66666667, 0.66666667, 1.125     ])

In [53]:
np.fmax(a,b)

array([5, 6, 9])

In [54]:
np.greater(a, b)

array([ True, False,  True])

In [55]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.mean(np_height)

1.7600000000000002

In [57]:
np.median(np_height)

1.73

In [58]:
np.std(np_height)

0.07429670248402682

In [59]:
np.corrcoef(np_height)

1.0

In [60]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\intelpython3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\intelpython3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use th

In [61]:
np.*?

np.ALLOW_THREADS
np.AxisError
np.BUFSIZE
np.CLIP
np.ComplexWarning
np.DataSource
np.ERR_CALL
np.ERR_DEFAULT
np.ERR_IGNORE
np.ERR_LOG
np.ERR_PRINT
np.ERR_RAISE
np.ERR_WARN
np.FLOATING_POINT_SUPPORT
np.FPE_DIVIDEBYZERO
np.FPE_INVALID
np.FPE_OVERFLOW
np.FPE_UNDERFLOW
np.False_
np.Inf
np.Infinity
np.MAXDIMS
np.MAY_SHARE_BOUNDS
np.MAY_SHARE_EXACT
np.MachAr
np.ModuleDeprecationWarning
np.NAN
np.NINF
np.NZERO
np.NaN
np.PINF
np.PZERO
np.RAISE
np.RankWarning
np.SHIFT_DIVIDEBYZERO
np.SHIFT_INVALID
np.SHIFT_OVERFLOW
np.SHIFT_UNDERFLOW
np.ScalarType
np.Tester
np.TooHardError
np.True_
np.UFUNC_BUFSIZE_DEFAULT
np.UFUNC_PYVALS_NAME
np.VisibleDeprecationWarning
np.WRAP
np.__NUMPY_SETUP__
np.__all__
np.__builtins__
np.__cached__
np.__class__
np.__config__
np.__delattr__
np.__dict__
np.__dir__
np.__doc__
np.__eq__
np.__file__
np.__format__
np.__ge__
np.__getattribute__
np.__git_revision__
np.__gt__
np.__hash__
np.__init__
np.__init_subclass__
np.__le__
np.__loader__
np.__lt__
np.__name__
np.__ne__
np.__

In [62]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C')

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Also
--------
zeros_like : Return an array of zeros with shape and type of input.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
full : Return a new array of given shape filled with value.

Examples
--------
>>> np.zeros(5)
array([ 0.,  0.,  0.,  0.,  0.])

>>> np.zeros((5,), dtype=int)
array([0, 0, 0, 0, 0])

>>> np.zeros((2, 1))
array([[ 0.],
      

In [63]:
np.absolute?


Call signature:  np.absolute(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'absolute'>
File:            c:\intelpython3\lib\site-packages\numpy\__init__.py
Docstring:      
absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the absolute value element-wise.

``np.abs`` is a shorthand for this function.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array